name: interval_time_picker
description: A variant of the default Flutter Time Picker in which you can pick intervals.
version: 1.0.0+3
homepage: https://github.com/Fleximex/interval_time_picker
repository: https://github.com/Fleximex/interval_time_picker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
