name: interval_time_picker
description: A variant of the default Flutter Time Picker in which you can pick intervals.
version: 0.1.0+1
homepage: https://github.com/Fleximex/interval_time_picker
repository: https://github.com/Fleximex/interval_time_picker

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter